### ISSUE TITLE
Add  MIDI Record Button and add Indian Music Notes name in Punjabi and Hindi

### ISSUE THREAD

**Issue by harminder31011973** [Bewelge/MIDIano#10]
Good work and thanks making this application 

Add Record button to record MIDI and add Indian Music Key Notes name in Punjabi and Hindi . so that Indian people can learn piano in their own language.

Thanks 
Harminder Singh

**Comment by Bewelge** [comment]
Hey there,

About MIDI recording: I may look into this in the future, but it's not currently planned.

About Indian key note names: Do you have a reference of the note names in the respective languages? This wouldn't be too much work but I didn't find any tables that show what the note names C/D/E.. or DO/RE/MI... are called in Hindi/Punjabi.

**Comment by Bewelge** [comment]
Feel free to open another issue if you can provide an answer about the Indian note names.
