### ISSUE TITLE
Adapting for Music AI

### ISSUE THREAD

**Issue by asigalov61** [Bewelge/MIDIano#11]
@Bewelge Hey @Bewelge 

I really liked MIDIano. It is perfect and sounds really good.

I was wondering if you would be interested in adapting your project for Music AI?

I desperately need someone to help with the front-end for my Music AI implementations and I was wondering if you would like to try it.

Here is my Music AI project that I would love to make front-end to:

https://github.com/asigalov61/GIGA-Piano

I am able to host the model and do everything except the front end so if you are interested, please let me know.

Sincerely,

Alex

**Comment by Bewelge** [comment]
Hey Alex,

just took a look at your project and it looks great! 

But I'm not entirely sure what you are looking for. Rebuilding the entire front-end of Midiano somewhere else would be too big of a project for me right now. I could imagine helping out with the rendering and/or implementing the output of your model into midiano directly. However, I would be hesitant to copy entire parts into a different project, as I haven't published/licensed the current version of it and am not planning to do so.

If you want to discuss details, you can contact me at contact(at)midiano.com.

Cheers,
Ben

**Comment by asigalov61** [comment]
@Bewelge Thanks. Will write to you shortly :)
