### ISSUE TITLE
Sound error on iphone's safari browser

### ISSUE THREAD

**Issue by diendv** [Bewelge/MIDIano#13]
I run on iphone safari is having no sound. although the device has sound on and plays .mp3 streaming music sites, there is sound. Can someone help explain this to me please. I really need help. Thank you

**Comment by Bewelge** [comment]
Hey, Can you provide more information on what version of iOS and which iPhone you're using?

**Comment by diendv** [comment]
Thank you @Bewelge early response!.
I am using iphone 11 Pro Max;  IOS 16.1.2
Currently, I am seeing if there is a machine that has a device. Devices with iOS version 16 and above are higher. And I am thinking is it because of safari browser webaudio. Currently I'm reading there is a document that says something like this https://curtisrobinson.medium.com/how-to-auto-play-audio-in-safari-with-javascript-21d50b0a2765. Don't know if you have solved this problem yet???

**Comment by Bewelge** [comment]
I'm a bit confused.

Are you experiencing the problem on midiano.com or on https://bewelge.github.io/MIDIano/ ? 

Or are you trying to build an application yourself and are having trouble with playing sound on iOS?

**Comment by Bewelge** [comment]
Please reopen if the issue persists. Cannot reproduce it myself.
