### ISSUE TITLE
minimize button is buggy

### ISSUE THREAD

**Issue by Neonunux** [Bewelge/MIDIano#15]
it's not possible to expand menu button after a minimize.

there is a typo in `js/ui/UI.js`, l. 25 and l. 234 in `refreshMenuHeight()`
```js
this.isMobile = window.matchMedia(
	"only screen and (max-width: 1600px)"
).matches
```

1600px should be 600 to define a mobile display

**Comment by Bewelge** [comment]
Merged a fix yesterday. Culprit was actually in the `maximizeMenu ` function
