### ISSUE TITLE
bug with scroll laptop touchpad

### ISSUE THREAD

**Issue by Neonunux** [Bewelge/MIDIano#18]
laptop touchpad sends a lot of event, overwhelming HandleScroll() in Player

![Animation](https://user-images.githubusercontent.com/2800474/212034557-dc34c411-b425-4d40-8c40-9f5302c0f14f.gif)

fixed by l.238 in Player.js
```js
this.scrollOffset = newScrollOffset
```
should be checked by
```js
if (!Number.isNaN(newScrollOffset)) { this.scrollOffset = newScrollOffset }
```

**Comment by Bewelge** [comment]
How can I reproduce this?

**Comment by Neonunux** [comment]
on a laptop, you scroll right/left on laptop&touchpad

**Comment by Bewelge** [comment]
fixed
