### ISSUE TITLE
[featuresuggestion] Marks for rehersal

### ISSUE THREAD

**Issue by pedjas** [Bewelge/MIDIano#24]
Great application.

Is it possible to add bookmarks at time line so specific parts can be easily repeated for learning? It could be quite simple, option for user to put mark on time line and on specific key restarts play from that mark.

**Comment by Bewelge** [comment]
Good idea. Any idea how it should handle having multiple bookmarks in one song? And do you have a preferred key?

**Comment by pedjas** [comment]
> Good idea. Any idea how it should handle having multiple bookmarks in one song? And do you have a preferred key?

It would be great to have an option to set multiple markers but only one may be set active so restart goes to that one.

Key to control that should be something that is easy to reach. Maybe Backspace?

**Comment by glococo** [comment]
Hi, +1 for this [**Enhacement**].
I would like to loop for example sheet 23 to 26, but can't with 0,1,2,3 hot keys. Also can't map 3s left right since can't be mapped.
Loooping through specific sheets will make me learn much intensive and be focus

**Comment by Bewelge** [comment]
I implemented a loop functionality so that you can play certain parts on repeat. Haven't gotten around to mapping of piano keys to function keys, so you'll have to use the computer keyboard for now.
