### ISSUE TITLE
Is it possible to load application with provided url for midi that should be played?

### ISSUE THREAD

**Issue by pedjas** [Bewelge/MIDIano#25]
Is it possible to run application and pass midi that should be played as parameter, like url to midi file?

**Comment by Bewelge** [comment]
It's not possible unless the linked site explicitly allows it or I serve the files through my own server. Not currently planning on realizing this.

**Comment by pedjas** [comment]
I thought to use it as support application for learning site, but, of course installed on my server to avoid using your resources.
In meanwhile, I learned that it is not possible to install it to other sites, so I have to give up that idea.

**Comment by Bewelge** [comment]
It would technically be possible but not legal, since I haven't published the Midiano source code under an open license (or any license). So please do not use the code without my authorisation.

**Comment by pedjas** [comment]
Of course I would not use code. I already said I have to give up an idea. Pitty.

**Comment by Bewelge** [comment]
You can now start up midiano by passing an URL to a midi file as URL param:

https://midiano.com/?songUrl=https://github.com/Bewelge/piano-midi.de-Files/raw/master/midi/elise.mid

The server serving the file needs to enable CORS for that to work though.
