### ISSUE TITLE
[featuresuggestion] Button to go to begining of the song

### ISSUE THREAD

**Issue by pedjas** [Bewelge/MIDIano#26]
Scrolling timeline to beginning is not easy with mouse, and gets harder with longer songs. Simple button that reverts to beginning would be helpful.

**Comment by Bewelge** [comment]
You can click on the timeline to jump to any part in a song. Will add a shortcut key to jump to the beginning though.

**Comment by pedjas** [comment]
> You can click on the timeline to jump to any part in a song. Will add a shortcut key to jump to the beginning though.

Yes, but going to very beginning of the song is hard to achieve with clicking on timeline.

Home key is great candidate for that purpose.

That said, why not add more keys to navigate timeline without mouse?

**Comment by gabrieltosta96** [comment]
@Bewelge other suggestions I think it would be great to have:

1- Having the list of hotkeys available.
2- being able to loop a specific block over and over again (that would help a lot on the practicing).

Also, I know this is not OS but I'd like to make myself available to help you with the implementations, =)

I really enjoy midiano and I think it is a great tool for learning piano

**Comment by Bewelge** [comment]
I added the hotkeys backspace to jump to the beginning of the song. Also the number keys 0-9 to jump to a specific part in the song.
I also added a button to view all hotkeys.
You can also disabled all hotkeys (incase you want to use the keys to play the piano).

@Gtosta96 Thanks! You can send me an E-Mail at "contact (a) midiano (d) com" to discuss :)
