### ISSUE TITLE
Clicking Sound

### ISSUE THREAD

**Issue by Bewelge** [Bewelge/MIDIano#3]
Do you hear the "clicking" sound when notes are turned off? Even in Mozart's Rondo alla Turka that is happening. Maybe the exponential ramp needs to go to a lower value before turning off possibly?

_Originally posted by @e7mac in https://github.com/Bewelge/MIDIano/issues/2#issuecomment-761896283_

I haven't noticed that actually. Can you point to an exact moment when it's happening? Then I can take a closer look. 

Maybe try adjusting the lookAhead time in Player.isNextNoteReached(time). The value decides how much in advance the note will be scheduled in the audio-context.

**Comment by e7mac** [comment]
I did some more testing and found that this is happening in Firefox, but works fine in Chrome. If you test on Firefox, it should be pretty easy to hear the clicking with the default midi file.

Also, curious if you know why this doesn't work on mobile Chrome?

**Comment by Bewelge** [comment]
Noticed the same behaviour yesterday. I managed to get rid of it mostly by replacing the setTargetAtTime with linearRampToValueAtTime  but that does seem to change the sound quite a bit, and I haven't checked how it behaves in Chrome then. I'll try to push a fix in the coming days.

**Comment by Bewelge** [comment]
Replacing the setTargetAtTime seems to have worked. Chrome mobile wasn't working because I used string.replaceAll. Fixed that too. Let me know if you notice anything else.

**Comment by e7mac** [comment]
Thanks! Looking real good now!

It still doesn't work on chrome/safari on iOS, although now android is working!
