### ISSUE TITLE
Launch with last Midi and input keyboard

### ISSUE THREAD

**Issue by glococo** [Bewelge/MIDIano#30]
Hi,
Thanks for this awesome WebApp.

I would like to remember the keyboard input, the song and track preferences like "requiere playalong" or sound level for each track.

Thanks :)

**Comment by Bewelge** [comment]
Track preferences are now saved for each song individually and should persist even after reloading. 

I'll also add a preference for starting with the last song on reload. What did you mean by remembering keyboard input? @glococo

**Comment by Bewelge** [comment]
Create a new issue if you still need help
