### ISSUE TITLE
Shortcuts to timestamps

### ISSUE THREAD

**Issue by gerb0n** [Bewelge/MIDIano#34]
I would like to have the possibility to add a shortcut to a specific timestamp. Especially for learning certain sections of a piece it would be nice to just tap on the 'shortcut' inside the progress bar and then just jump towards that timestamp.

Would be even more awesome if you could also specify if you want to 'infinitly loop' between two points.

https://i.imgur.com/RyK7HSi.png

**Comment by Bewelge** [comment]
Hey there, I added a loop functionality just yesterday. It's under Settings->General->Loops. It allows you to define a range of measures which will then repeat automatically. It's not saved specifically for each song though.  Would you still need bookmarks on top of that? Might implement that in the future then.

**Comment by gerb0n** [comment]
What a coincidence! The loop functionality is perfect and exactly what I was looking for. Hats off to you sir, great platform / product!

**Comment by Bewelge** [comment]
Haha yea sure is a coincidence. That feature request was open for a couple of months. I initially thought you were commenting on it 😄 Glad you find it useful.
