### ISSUE TITLE
MIDI device detection issue

### ISSUE THREAD

**Issue by KieranGreenwood** [Bewelge/MIDIano#38]
Recent bug since last update I think.

The app only detects midi device for the first session. 
When the browser is closed and the app loaded later, no MIDI devices are detected.

To fix: go into dev tools > application > storage > clear site data, then reload the app and it works again. 
(But only for the first session, then it needs fixing every time which loses settings/song imports)

Windows 11 chrome 119 yamaha p125

_(Killer app by the way, really well done its great)_

**Comment by Bewelge** [comment]
Hey, thanks for the kind words first of all! 

I can't really reproduce the issue on my end but I just pushed a fix in an attempt to fix it. I believe it was a timing issue of the UI being generated before the MIDI access was granted. Let me know if it works better now. 

If not, could you post the content of the console when it isn't working?

**Comment by KieranGreenwood** [comment]
Cannot re-create the problem now. Looks like the fix worked! Thank you :)

**Comment by Bewelge** [comment]
Great, thanks for reporting the issue!
