### ISSUE TITLE
Suggestion: make this reusable for kalimba

### ISSUE THREAD

**Issue by mnlbox** [Bewelge/MIDIano#4]
Hi,
I'm currently looking for a way to use this tools for Kalimba. I see in the online version that a option exist for choose Instrument and it's also contains Kalimba but when I change that I can't see any diffrence.
How can I use this for Kalimba (with 17 keys for example) Is it possible currently?

**Comment by Bewelge** [comment]
Hey there,
You can change the instrument of the individual tracks of a song in the "Tracks"-menu. To change the instrument of the keys you are playing through a MIDI-Device or over the on-screen keyboard you have the setting "Your Instrument" under "Settings -> General".

Note that this only affects the output-sound though. So you can only hear a difference, not see it ;-)

Let me know if that helps.

**Comment by pedjas** [comment]
For Kalimba it would be helpful if note names are displayed using Kalimba notation.
