### ISSUE TITLE
Loop mode offset & input

### ISSUE THREAD

**Issue by KieranGreenwood** [Bewelge/MIDIano#41]
These two are pretty minor.

One thing that keeps catching me out. The loop start/end measures are offset by 1, If i choose start at 20, it starts from 21 etc...(zero-indexed array?) It would be nice if the numbers matched the visuals.

I feel like it would be easier if there was the option to type measure numbers in instead of just a range slider.

**Comment by Bewelge** [comment]
I agree with both. Will get on it

**Comment by Bewelge** [comment]
Added number inputs to all sliders and changed the indexing of the loops. Start: 1, End:1 will now loop Measure 1. Start: 1, End: 2 will loop the first two measures etc.
