### ISSUE TITLE
Feature suggestion: count in

### ISSUE THREAD

**Issue by KieranGreenwood** [Bewelge/MIDIano#42]
A setting that enables a 'count in' feature that does a 1-2-3 tick count before a track starts/resumes. 

In loop mode I've tried the delay between loops option but i struggle to get the timing right with it being silent. It's also not clear where the delay starts from as there is a delay at the end of the loop, a visual rewind, then a pause before starting.

My current workaround is starting a measure or two early as a cue to the bit I actually want to start at.

**Comment by Bewelge** [comment]
I've added the option to have a metronome tick X beats before starting. You can also set the amount of beats. Reopen if it doesn't work for you :)
