### ISSUE TITLE
WebMIDI support of Safari

### ISSUE THREAD

**Issue by NitroCodez** [Bewelge/MIDIano#43]

**Comment by NitroCodez** [comment]
I’m on an iPad, and I have connected it to my piano, and I am using Firefox, but for some readeon the website is not discovering my piano. It always says no MIDI devices found. Please help

**Comment by Bewelge** [comment]
Hey there, sadly Apple hasn't implemented the WebMIDI API in Safari (both mac and iOS) yet - https://caniuse.com/midi 

So I'm afraid currently there's no way to use a MIDI device over the browser on iOS. I also don't have an iPad to test out alternatives. But I'll keep this issue open incase something changes

**Comment by NitroCodez** [comment]
Yes, I know it does not support safari, but as I said, I am using the Firefox app. I also tried it on chrome. They are different apps than safari. Does this not change anything?

**Comment by Bewelge** [comment]
Sadly your choice of browser doesnt make a difference. 

![image](https://github.com/Bewelge/MIDIano/assets/17884995/340f4bf1-b206-4a71-b261-1a8fc34aafc3)


Chrome is based on Chromium while Safari is based on Webkit. Now Apple only allows browsers on iOS that are based on Webkit, so Chrome on iOS is a special version based on Webkit, meaning its capabilities are not the same as Chrome on windows/android/whatever.  Its capabilities are not identical to Safari but so close that CanIUse seems to put them in the same category.

You can check for "Other browsers on iOS" more specifically in this list https://caniuse.com/?compare=chrome+49,safari+9,safari+9.1,ios_saf+9.0-9.2,ios_saf+9.3&compareCats=all

Sadly, none of the browsers on iOS support Web MIDI

**Comment by NitroCodez** [comment]
Oh. I get it now. Well thank you for clarifying and for your support!
