### ISSUE TITLE
HQ Piano soundfont is not applied to the MIDI instrument nor virtual piano

### ISSUE THREAD

**Issue by jacobopantoja** [Bewelge/MIDIano#45]
At least in Firefox 121 on Win10 1809, the HQ piano soundfont is only applied to the MIDI file being played, not to the MIDI instrument nor the virtual piano (the one you can play with the mouse)

**Comment by Bewelge** [comment]
I think that's a caching problem. Can you try clearing your cache? 

Open dev tools -> Storage -> Cache Storage -> delete the entries for app.midiano.com

Let me know if that works.

**Comment by jacobopantoja** [comment]
Same result.

Also tested in another computer, freshly opened for the first time, also Firefox 121 but Win11. Same result

**Comment by Bewelge** [comment]
I just noticed something: 

The default input instrument is acoustic_nylon_guitar and not acoustic_grand_piano. The HQ Soundfont only works for acoustic_grand_piano. Could that be the reason?

I'll change the default back to piano with the next update.

**Comment by jacobopantoja** [comment]
_Touché_. I'm sorry that I didn't see that I could change the instrument.

Thanks a lot
