### ISSUE TITLE
Metronome pitch

### ISSUE THREAD

**Issue by Romenek** [Bewelge/MIDIano#46]
I'm used to a metronome where the first beat is a high note and the others are low, here it seems reversed. Almost everything can be set, but perhaps not the velocity and pitch for the metronome. Perfect application, great that it works without registration.

**Comment by Bewelge** [comment]
You're right I just gave it a try switching the two sounds and it sounds much better. Will push that with the next update, hopefully this week :)

**Comment by Bewelge** [comment]
Just added this with the last update. Let me know if you're still having trouble with it
