### ISSUE TITLE
b instead of #

### ISSUE THREAD

**Issue by Gui-Tahar** [Bewelge/MIDIano#5]
Hi,
Your app is the best ;-)
Now, I use it for my students.
Just a little correction with blackkeys name (flat instead of sharp).
![sharp](https://user-images.githubusercontent.com/82437884/114516788-04f4f580-9c3e-11eb-9d5e-60cdcbbabc88.png)

Thanks for your job!

**Comment by Bewelge** [comment]
Hey,
thanks, that's very nice to hear :-)
And thank you for pointing that out, I have just pushed an update to fix the naming. I also added an option to display the black keys as either sharps or flats.

Let me know if you find any more bugs or have any other suggestions for improvement.
