### ISSUE TITLE
Add a wait mode (pauses until the user plays a key)

### ISSUE THREAD

**Issue by casterkay** [Bewelge/MIDIano#51]
I think it would be very beneficial to add an option of wait mode, so that the music pauses at every note/chord until the user plays the right keys.

**Comment by Bewelge** [comment]
It exists, it's the playalong feature. You can enable it in the track menu on a per-track basis. There are also hotkeys to quickly toggle it for the first two tracks.

**Comment by casterkay** [comment]
Thank you for pointing it out!
