### ISSUE TITLE
External MIDI piano velocity

### ISSUE THREAD

**Issue by jacobopantoja** [Bewelge/MIDIano#52]
It looks like in my piano, the velocity (i.e. the intensity of each note) is kept constant. I've seen that it is not (at least that I can see) my instrument, since in other MIDI apps the velocity is properly recognized.

Is it possible to implement that?

**Comment by Bewelge** [comment]
Thanks for pointing that out, I usually mute Midiano when using my keyboard - I simply forgot to implement that.

Just pushed a fix!

**Comment by jacobopantoja** [comment]
Wow, you're the best! Thanks a lot
JPantoja

**Comment by Bewelge** [comment]
Happy to help :) Was a quick fix
