### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by Yvant2000** [Bewelge/MIDIano#56]
When using midiano in [Zen browser](https://zen-browser.app), I get the message 

Failed to load soundfonts. There will be no sound output.
Error :
TypeError: NetworkError when attempting to fetch resource

![image](https://github.com/user-attachments/assets/309e4184-ddd7-4d40-a3e3-99b0ff9338c4)

By setting an output device, I can get sounds anyway, but I can't close this message box.

**Comment by Bewelge** [comment]
Hmm, I just downloaded the Zen browser and it works fine for me there, so I don't think it's an issue with your browser. 

Maybe a stupid question, but have you tried reloading the page? The error message suggests a network error when retrieving the sound files, which could have several reasons.

**Comment by Yvant2000** [comment]
Reloading the page didn't work, but after deleting all the cache and memory in my browser, it now works.
There was probably something I did wrong on my side. Sorry for the useless issue, and thanks for your time !

**Comment by Bewelge** [comment]
No worries! Happy that it works now :)
